---
driver:
  name: scalr
  scalr_api_key_id: 'APIK7L286BTSSLR9SACF'
  scalr_api_key_secret: 'QxwRBGi4aIiCaUWRKmoOrLx55WW4Y4uy0CrhEkUv'
  scalr_api_url: 'http://demo.scalr.club'
  scalr_env_id: '6'
  scalr_project_id: '1682b63d-6d28-4b5f-8438-3cf058f89a6c'
  scalr_server_instanceType: 't2.medium'

  scalr_platform: 'ec2'
  scalr_location: 'us-east-1'
  scalr_base_farm_role:
    security:
      securityGroups:
        - id: 'sg-03049e48'
    networking:
      networks:
        - id: 'vpc-5818a621'
      subnets:
        - id: 'subnet-956d5ea9'


provisioner:
  name: shell

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
  driver:
      scalr_use_role: 1
- name: centos7
  driver:
      scalr_use_role: 96624

suites:
  - name: default
    run_list:
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
