version: '3'
services:
  webhook:
    build: .
    container_name: variable-webhook
    ports:
      - "5018:5018"
    volumes:
      - /opt/scripts:/opt/scripts
      - /var/log/webhook:/var/log/webhook
